# installation paths
SHAREDIR := /usr/share/selinux

AWK ?= gawk
NAME ?= $(strip $(shell $(AWK) -F= '/^SELINUXTYPE/{ print $$2 }' /etc/selinux/config))

MLSENABLED := $(shell cat /selinux/mls)
ifeq ($(MLSENABLED),)
	MLSENABLED := 1
endif

ifeq ($(MLSENABLED),1)
	TYPE ?= mcs
endif

ifeq ($(NAME), mls)
	TYPE ?= mls
endif

HEADERDIR := $(SHAREDIR)/devel/include
include $(HEADERDIR)/Makefile

